### PR TITLE
Bug #1157 Wrong GPS time in simulator GNSS logs

### PR DESCRIPTION
**Pull request by mercom**
Bug #1157 Wrong GPS time in simulator GNSS logs

UTC and GPS difference should be 18seconds.
This should be reported in the relevant message field UTC-offset.
Both times in the TIMEA logs should be aligned to the "simulated" time
not the system time.

Based on the #1158 change.

### CODE REVIEW

**Comment by TanguySoto** [comment]
@mercom How should I review this? I see you have it based on the other MR? Should we merge them one by one?

**Comment by mercom** [comment]
@TanguySoto  once the #1158 has been verified and merged, I shall rebase this one (#1157).

**Comment by TanguySoto** [comment]
> 
> 
> @TanguySoto once the #1158 has been verified and merged, I shall rebase this one (#1157).

@mercom  Merge of #1158 done. You can rebase :)

**Review by TanguySoto — APPROVED** [review]

**Comment by dmarszk** [comment]
Looks like this produces an inconsistent test - https://gitlab.com/esa/NMF/nanosat-mo-framework/-/jobs/1792883046

@mercom can you check this praticular run?

**Pull request merged**
