### PR TITLE
Issue 1119 Code formatting and linting

### PR DESCRIPTION
**Pull request by OrangeLightning219**
This pull request contains configurations for formatting and linting plugins.
Possible maven options:
- `-Dspotless.apply.skip` - skip formatting
- `-Dspotless.check.skip` - skip checking if formatting is correct
- `-Dspotbugs.skip` - skip linting

### CODE REVIEW

**Comment by CesarCoelho** [comment]
Hi,

Please update the style to something more concise. The new style is increasing the files by around 20%, without any actual logic, just almost empty lines with brackets.
I propose that you use the methods, classes, if-then-else style as: 

```
    public static int getTimeFactor() {
        return usePlatformClock ? platformClockCallback.getPlatformTimeFactor() : 1;
    }
```

and

```
            if (System.getProperty(HelperMisc.PROP_ORGANIZATION_NAME) != null) {
                networkString = networkString.concat(System.getProperty(HelperMisc.PROP_ORGANIZATION_NAME));
            } else {
                networkString += "OrganizationName";
            }
```

So the bracket must be on the same line as the statement/condition.

**Comment by dmarszk** [comment]
@CesarCoelho can you have a look now?

**Comment by CesarCoelho** [comment]
Hi @OrangeLightning219 ,

It is looking much better now but there are still 2 more things:

1. The arguments in the methods are being spaced when there is a new line. This causes the methods to look awkward:
Example here: 
https://github.com/esa/nanosat-mo-framework/commit/054afb3527313f2bafdf64318722e8722f71f2f1#diff-9047dd67d021f1e8245373db5895b3a056ebb4c7de317f16c55ecd074af3e13dR115

Can you check if there is a way to make it not do that and just write on the next line without adding extra spaces?

2. When there are nested dots to call functions, it seems that the auto-formater breaks them down per line.
Example here:
https://github.com/esa/nanosat-mo-framework/commit/054afb3527313f2bafdf64318722e8722f71f2f1#diff-53253e3344dbc5edb28891c35939bc2e6e5714a4a0d2656e9a0a4d9edf6d592dR56
 
and here:
https://github.com/esa/nanosat-mo-framework/commit/054afb3527313f2bafdf64318722e8722f71f2f1#diff-5e71e02621d1e3ceb3a6a0498b6e0febc162f5224e0c58156fca4b56fae29817R148

Can you force it to remain in the same line?


Thanks in advance!  :)

**Comment by OrangeLightning219** [comment]
@CesarCoelho I made the changes you requested.

**Pull request merged**
