### PR TITLE
Bug #39 [COM Archive] Remove eclipselink

### PR DESCRIPTION
**Pull request by CesarCoelho**

### CODE REVIEW

**Comment by dmarszk** [comment]
@CesarCoelho see below comments:
- Please remove the commits not relevant to this PR
- Reference the respective issue from the commit and the PR - https://gitlab.com/esa/NMF/nmf-issues/-/issues/39 - see contribution [instructinos](https://github.com/esa/nanosat-mo-framework/blob/dev/CONTRIBUTING.md)
- Rebase on top of dev
This will allow us to test and review it easily

**Comment by dmarszk** [comment]
@CesarCoelho please migrate the LastArchiveSync entity into a COM Object of the ArchiveSync service.
Note that if the deprecated classes do not function anymore, it makes no sense to deprecate them.

**Review by lstochlak — COMMENTED** [review]
LastArchiveSyncEntity is necessary for nmf ops-sat (GroundMOProxyOPSSATImpl). See @dmarszk comment.

**Comment by CesarCoelho** [comment]
You can merge this into the dev branch, I have added the LastArchiveSync into the xml as discussed above, check the commits. I don't know what are the changes that you might have to do on the OPS-SAT branch to make it work, but I assume nothing major.
The LastArchiveSync entity was a hack that should have never been added in the first place as it is going around the frontend interfaces, and sneaking in into the database.

**Comment by OrangeLightning219** [comment]
@CesarCoelho There are some conflicts with the dev branch, can you resolve them? @dmarszk Łukasz and I will make necessary changes in ops-sat and lwmcs.

**Comment by CesarCoelho** [comment]
@OrangeLightning219 I just rebased it. Can you merge it now? I want to use this optimization in Phi-Sat-2, so I need it to be merged asap. Thanks

**Comment by OrangeLightning219** [comment]
@CesarCoelho I pushed some changes that will allow lwmcs to run properly (we use postgres there so the sql syntax is a little bit different). Also I fixed a bug in the `QueryCallable` class - the fields in the query were in a wrong order.

I could merge it but I think @dmarszk should approve this change before.

**Comment by CesarCoelho** [comment]
@OrangeLightning219  Looking good, thanks!

**Comment by CesarCoelho** [comment]
@lstochlak Any progress on this? I would like to use it as soon as possible  :)

**Comment by OrangeLightning219** [comment]
@dmarszk The pull request in NMF OPS-SAT is ready. We also made necesary changes in LWMSC and will merge them after you merge this pull request.

**Pull request merged**
