### PR TITLE
Remove redundant local variable.

### PR DESCRIPTION
**Pull request by arturobernalg**

### CODE REVIEW

**Review by TanguySoto — COMMENTED** [review]
I tend to be in favor of these changes but I could understand why in some places the variable names helps to understand what is returned.

@dmarszk @mercom What do you think?

**Comment by mercom** [comment]
@TanguySoto - looking at the previous code, the variable names did not add much. You probably get better info from the method's names that it is using to fetch the values from. However it would be nice to have more meaningful javadoc on the methods, as currently many of them do not explain what the parameter actually are or what it will return. 
@arturobernalg could you improve the javadocs perhaps?

**Comment by arturobernalg** [comment]
> @TanguySoto - looking at the previous code, the variable names did not add much. You probably get better info from the method's names that it is using to fetch the values from. However it would be nice to have more meaningful javadoc on the methods, as currently many of them do not explain what the parameter actually are or what it will return.
> @arturobernalg could you improve the javadocs perhaps?

Hi @mercom 
I'll do my best.  When I finish the javadoc I will close this PR.
TY

**Comment by dmarszk** [comment]
@arturobernalg this needs manual rebase

**Comment by arturobernalg** [comment]
> @arturobernalg this needs manual rebase

Hi @dmarszk 
rebased. Sorry for the delay.
TY

**Review by TanguySoto — APPROVED** [review]

**Pull request merged**
