### PR TITLE
[GroundMOAdapterImpl] Make action-instance-ID unique

### PR DESCRIPTION
**Pull request by X52p**
Adds a Method to create Unique action-instance IDs,
also changed the return statement of invokeAction to Long to be able to return the instance ID

### CODE REVIEW

**Comment by X52p** [comment]
I now changed the generation method to be more efficient (It now uses shifts, but I kept the random number using javas Random class). Also I added a test.

**Comment by CesarCoelho** [comment]
Hi Kevin,

The HelperCOM class has:
  private static final long EPOCH2020 = 1577836800;
  private static final Random RNG = new Random(System.nanoTime());
  private static final AtomicInteger objectInstanceIdCounter = new AtomicInteger(0);
  private static long lastObjectInstanceIdTimeStamp = 0;

Can you move those variables and your method to a dedicated class to generate the unique instances?
I don't think that the HelperCOM is the right place.
You probably should have a singleton class to generate your unique ids. Look it up online how to make a Singleton class in java.

**Comment by X52p** [comment]
what would be the advantage of a singleton class over a class with static members in this case?

**Comment by CesarCoelho** [comment]
It's a Helper class, it should be stateless. It was stateless before, that should not be changed.
Generating sequential ids needs you to hold the state of the previous id. So, you are adding some code to the Helper class to do that, making it stateful.
Check here: https://dzone.com/articles/stateful-or-stateless-classes

Please move the generation of ids to a dedicated stateful singleton class and leave the Helper as stateless. The code will be cleaner, less cryptic, and people in the future won't ask "why is this Helper class stateful?".

**Comment by X52p** [comment]
I understand the reason for moving it to an other class, I just would like to know, what the advantage would be, when it is moved to a singleton class over moving it to a Static class (I did't found any advantage that applies in this specific case)

**Comment by CesarCoelho** [comment]
You mean in terms of performance?

**Comment by X52p** [comment]
no, from a software architecture perspective. There are no Interfaces that need to be implemented or other classes that it needs to be inherited from and there are also no other reasons (as far as I can see it) that would require an Object instance.

**Comment by CesarCoelho** [comment]
The code will be cleaner.
Also, "They permit lazy allocation and initialization, whereas global variables in many languages will always consume resources." from:
https://stackoverflow.com/questions/2969599/why-use-singleton-instead-of-static-class

**Comment by X52p** [comment]
Interesting, I did't thought about lazy allocation. I moved it to a singleton now.

**Comment by CesarCoelho** [comment]
The code is looking better now!  :)
A few more changes:
1. Add the License Header on the ObjectInstanceIdGenerator.java file
2. Add some description to the methods' signature

I think after that, you are good to go!

**Comment by dmarszk** [comment]
Looks good to me. @CesarCoelho ?

**Comment by X52p** [comment]
I added some descriptions  and the Licence now.

**Comment by CesarCoelho** [comment]
@dmarszk , @X52p Looking good!

**Pull request merged**
