### PR TITLE
Wiki updates

### PR DESCRIPTION
**Pull request by X52p**
Updated Wiki entries that were out of date because of name changes and Maven updates.
Some variables in the section `Developing your first NMF App` were renamed to achieve a more consistent naming scheme.

### CODE REVIEW

**Comment by dmarszk** [comment]
Thanks! Two comments to address:
- Seems like the Supervisor rename is not complete - new POM is added under:
https://github.com/esa/nanosat-mo-framework/blob/wiki-updates/core/nmf-composites/nanosat-mo-supervisor/pom.xml
but there is still a POM + code there:
https://github.com/esa/nanosat-mo-framework/tree/wiki-updates/core/nmf-composites/generic-nanosat-mo-supervisor
- Please start commit title with a capital letter and try to include information on the element modified. Example title:
`rename variable`
Is less beautiful than:
`Wiki: Rename example variable`
or
`[wiki] Fix example code`
and
`rename subproject`
could be 
```
[nmf-supervisor] Rename the project

The supervisor has no generic and mission-specific
parts anymore, thus the "generic" name part was removed.
```

**Comment by CesarCoelho** [comment]
Hi Kevin,

I noticed that on pull request #18, you removed this from the POM file:
    <module>nanosat-mo-supervisor</module>

Any plans on adding it again? :)

**Comment by dmarszk** [comment]
Can you rebase on top of dev so we can see if the build pipeline success? :)

**Comment by X52p** [comment]
Hi, I rebased it onto the dev branch. I hope that I did that correctly. Please tell me if I should do something differently :)

**Pull request merged**
