### PR TITLE
Apps launcher

### PR DESCRIPTION
**Pull request by yannickl96**
This PR addresses the following issues:

* Bug #523: Propose and implement COM Archive data persistence/rotation policy for space apps
* Bug #524: Save application's console output in the Supervisor's archive

Remarks to the implementation of #523: After finishing ArchiveSync, the ArchiveSync provider queries the archive and deletes all instances of ParameterValue and AggregationValue.

### CODE REVIEW

**Comment by CesarCoelho** [comment]
This should not be classified as a "Bug" but as a "Feature"/"Enhancement".
What is the default policy? To delete the Archives automatically? You must document this.

Also, this should be an optional feature and "selectable" via configuration flags. One might not want automatically deletion of content of the remote archive after sync.

**Comment by yannickl96** [comment]
Hi Cesar,
I flagged it as a bug as it's tracked in the Bug category in Redmine. The default behaviour is that the archive fills up indefinitely. Therefore, your proposed scenario of an app outputting error messages all the time will take up quite a lot of disk space. That's why I implemented the deletion of entries after archive sync. It does not delete the whole archive but ParameterValue and AggregationValue COM objects and is easily extendable, to for example delete the standard output entries (I will also add this, good point there!). As this only happens after archive sync, the data is not lost but persisted at whatever component which is the consumer of the ArchiveSync service (e.g. Ground MO Proxy).

**Comment by CesarCoelho** [comment]
Hi Yannick,

Your reply is a bit intertwined. There are two separate issues/questions here:
1. Default policy/behavior action for after the sync:   delete/keep
2. Apps standard output being stored as a file.

My two comments are separate. Can you address both in two separate messages?
Thanks.

**Comment by yannickl96** [comment]
Hi Cesar,
the issues are a little bit intertwined, but I will separate it.
Concerning question 1:
The default behaviour without my implementation is to keep all archive entries after sync. As the archive stores published parameter values, aggregation values and e.g. values passed in setParameter operations it will fill up and, therefore, monotonously increase in size, ultimately filling up all disk space in the worst case. Therefore, the feature to clean the database of such values was implemented. After executing an archive sync, you don't need to persist, e.g. ParameterValues in the space segment anymore, as the data is then available and persisted in the ground segment. E.g.: Running payloads-test for half an hour results in a 7MB archive database without any interaction with the app. Purging just parameter values and aggregation values reduces the size of the archive back to around 100KB. 
I will add the option to make this feature configurable, though.

**Comment by yannickl96** [comment]
2. As of now, I did not impose a limit on the stdout/stderr stored in the archive. The main reason of implementing is that unexpected (not mentioned in catch-clauses) exceptions are not logged by the java logging mechanism but get pumped into stdout. Let's consider the example of an app causing an OutOfMemoryException. We have no way to see it, except for checking stdout which we persist in the COM archive with the new feature. Imposing a size limit on the archive is a valid idea, I will consider the pro's and con's of it.

**Comment by CesarCoelho** [comment]
1. Ok, got it. Yes, it is better to make it configurable.

2. I was imagining that the stdout was being stored as a file, now I understand that you are actually storing it in the COM Archive of the supervisor. I was not suggesting to impose a limit on the archive itself, but on the stdout content. For example, if you send an app with a "retarded" while loop printing log messages, this will easily fill up the COM Archive on the supervisor and blow it up, no?
My suggestion is to somehow limit this output and to have a "cut-off" limit. If the outputted content is greater than x MB, then don't store more text and just write something like "Stdout Limit reached. Please reduce the verbose of this App."
Other alternative is to make the condition based on the number of outputted lines: If more than 10'000 lines, then stop storing the stdout.

**Comment by CesarCoelho** [comment]
By the way, I am not sure if you had a look on the ArchiveSync algorithm itself.
A very simple way to save a lot of bandwidth during the sync is to add a compression algorithm on it. When I coded the sync mechanism I was very short on time, so I didn't finish the compression part. I left the hook here:
https://github.com/esa/nanosat-mo-framework/blob/master/core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/provider/ArchiveSyncProviderServiceImpl.java#L308

You could probably save quite some bandwidth with not too many lines of code.
You can use a simple ZIP stream which is already available with the java framework itself, so you wouldn't need any external third-party libraries. You probably can use ZipOutputStream or GZipOutputStream where I pointed out.
If you do it, please add a log message to know the compression ratio, this is a very interesting metric to log and to know, specially for the CCSDS and its future activities.

**Comment by yannickl96** [comment]
I implemented the configuration option for storage of STDOUT and STDERR in the archive and also an option to enable disable archive vacuuming after archive sync. 
I furthermore enforced a quota on the archive for STDOUT/STDERR content which can be configured. All together I added three configuration properties to the supervisor's provider.properties with their respective default values:

esa.mo.nanosatmoframework.storestd=true
esa.mo.nanosatmoframework.purgearchive=true
esa.mo.nanosatmoframework.stdlimit=2048

**storestd** describes if stdout/stderr should be persisted in the supervisor's COM archive.
**purgearchive** describes if the archive should be cleaned after archive sync.
**stdlimit** describes the maximum amount in KiB of stdout/stderr **per app** that shall be persisted in the archive.

**Pull request merged**
